folio-org/mod-data-import-converter-storage

Dockerfile, descriptors/ModuleDescriptor-template.json
Use new Alpine base docker image with more recent Java 8 (222) with +UseContainerSupport, and JAVA_OPTIONS MaxRAMPercentage to manage container memory.
See notes at [FOLIO-2358](https://issues.folio.org/browse/FOLIO-2358).
=> MODDICONV-84 FOLIO-2358 manage container memory

mod-data-import-converter-storage-server/src/main/java/org/folio/rest/impl/ModTenantAPI.java, mod-data-import-converter-storage-server/src/main/resources/templates/db_scripts/data-migration/update_data_types.sql, mod-data-import-converter-storage-server/src/main/resources/templates/db_scripts/schema.json, mod-data-import-converter-storage-server/src/test/java/org/folio/rest/impl/DefaultJobProfileTest.java, mod-data-import-converter-storage-server/src/test/java/org/folio/rest/impl/JobProfileTest.java, mod-data-import-converter-storage-server/src/test/java/org/folio/rest/impl/association/CommonProfileAssociationTest.java, mod-data-import-converter-storage-server/src/test/java/org/folio/rest/impl/snapshot/JobProfileSnapshotTest.java
Change record type MARC for more specific type, like MARC_BIB, MARC_AUTHORITY, MARC_HOLDING
- created script for migration data type from marc to marc_bib
- updated tests
- pull raml storage with new values for data types
[MODDICONV-187](https://issues.folio.org/browse/MODDICONV-187)
=> MODDICONV-187 Store MARC Authority record

.rancher-pipeline.yml, mod-data-import-converter-storage-server/src/main/java/org/folio/rest/impl/ModTenantAPI.java, mod-data-import-converter-storage-server/src/main/resources/templates/db_scripts/data-migration/return_data_types.sql, mod-data-import-converter-storage-server/src/main/resources/templates/db_scripts/schema.json, mod-data-import-converter-storage-server/src/test/java/org/folio/rest/impl/DefaultJobProfileTest.java, mod-data-import-converter-storage-server/src/test/java/org/folio/rest/impl/JobProfileTest.java, mod-data-import-converter-storage-server/src/test/java/org/folio/rest/impl/association/CommonProfileAssociationTest.java, mod-data-import-converter-storage-server/src/test/java/org/folio/rest/impl/snapshot/JobProfileSnapshotTest.java
reverting data type changes to generic MARC according to the https://issues.folio.org/browse/MODDICONV-191
- changed back data type to generic MARC
- fixed tests
=> MODDICONV-191 - Change dataType to have have common type for MARC related subtypes

NEWS.md, mod-data-import-converter-storage-server/src/main/resources/templates/db_scripts/defaultData/default_marc_holdings_job_profile.sql
In the scope of https://issues.folio.org/browse/MODSOURCE-336 the default mapping is required to create an Inventory Holdings. It is not expected that after this PR is merged user will see created Holdings.  
* created default mapping profile for MARC_HOLDINGS
* created action profile for MARC_HOLDINGS
* added linkage between job <-> action profile
* added linkage between action <-> mapping profile
=> MODDICONV-199 - Add default mapping profile to default Holdings profile

NEWS.md, mod-data-import-converter-storage-server/src/main/java/org/folio/dao/association/CommonProfileAssociationDao.java, mod-data-import-converter-storage-server/src/main/java/org/folio/dao/association/ProfileAssociationDao.java, mod-data-import-converter-storage-server/src/main/java/org/folio/services/AbstractProfileService.java, mod-data-import-converter-storage-server/src/main/java/org/folio/services/JobProfileServiceImpl.java, mod-data-import-converter-storage-server/src/main/java/org/folio/services/association/CommonProfileAssociationService.java, mod-data-import-converter-storage-server/src/main/java/org/folio/services/association/ProfileAssociationService.java
When removing an action profile from a job profile, sometimes that will cause that action profile to be removed from all job profiles it is associated with. Need to fix it
Table match_to_action_profiles contains field jobExecutionId, that need to be included in delete query to delete only profile associated with particular job execution profile. Also delete sql query should not fail, if  jobExecutionId is not presented in jsonb, because other mapping tables do not contain jobExecutionId
=> MODDICONV-204. When removing an action profile from a job profile, it sometimes removes that action from ALL job profiles

mod-data-import-converter-storage-server/pom.xml, pom.xml
Upgrades
RMB to 33.2.1 (includes log4j vulnerability fix)
Vert.x  to 4.2.1
folio-di-support to 1.4.1
=> Upgrade to RMB v33.2.1

NEWS.md, pom.xml
to fix the vulnerability that is present in log4j<= 2.14
* upgrade log4j version to 2.16.0
[MODDICONV-218](https://issues.folio.org/browse/MODDICONV-218)
=> MODDICONV-218 - Juniper R2 2021 - Log4j vulnerability verification and correction

mod-data-import-converter-storage-server/src/main/resources/templates/db_scripts/defaultData/default_update_marc_holdings_job_profile.sql
FOR Action Profile, Default - Create MARC holdings > Change Description
This action profile is used with FOLIO's default job profile for creating Inventory Holdings and SRS MARC Holdings records. It cannot be edited, duplicated, or deleted.
[MODDICONV-231](https://issues.folio.org/browse/MODDICONV-231)
=> MODDICONV-231 Change to default - Create MARC holdings action profiles

pom.xml
Using the latest versions helps us avoid possible problems with the libraries.
- Overidded log4j for fix critic vulnarebility to 2.17.0 version
- Create a task to upgrade the rmb and vertx dependencies for Morning Glory
[MODDATAIMP-635](https://issues.folio.org/browse/MODDATAIMP-635)
=> MODDATAIMP-635 Check if any 3d party dependencies should be update for DI modules

NEWS.md, mod-data-import-converter-storage-server/src/main/java/org/folio/rest/impl/DataImportProfilesImpl.java, mod-data-import-converter-storage-server/src/main/java/org/folio/services/AbstractProfileService.java, mod-data-import-converter-storage-server/src/main/java/org/folio/services/ProfileService.java, mod-data-import-converter-storage-server/src/test/java/org/folio/rest/impl/DefaultActionProfileTest.java, mod-data-import-converter-storage-server/src/test/java/org/folio/rest/impl/DefaultJobProfileTest.java, mod-data-import-converter-storage-server/src/test/java/org/folio/rest/impl/DefaultMappingProfileTest.java, mod-data-import-converter-storage-server/src/test/java/org/folio/rest/impl/DefaultMatchProfileTest.java
Tag doesn't attach to default DI profiles
- Compare entity with profile from database, exclude metadata and tags to avoid update other properties default profile except tags.
- Implement updating single property using http patch method to prevent using put as in this case.
[MODDICONV-235](https://issues.folio.org/browse/MODDICONV-235)
=> MODDICONV-235 Adding a tag to some profiles displays an error message and a success message

mod-data-import-converter-storage-server/pom.xml, pom.xml
Update RMB from 33.2.2 to 33.2.8.
The RMB update indirectly updates jackson-databind from 2.11.4 to 2.13.2.1 fixing https://nvd.nist.gov/vuln/detail/CVE-2020-36518
Update Vert.x from 4.2.1 to 4.2.6.
The Vert.x update indirectly updates Netty from 4.1.69.Final to 4.1.74.Final fixing https://nvd.nist.gov/vuln/detail/CVE-2021-43797
Update log4j from 2.17.0 to 2.17.2 fixing https://nvd.nist.gov/vuln/detail/CVE-2021-44832
Update junit from 4.13 to 4.13.2 fixing https://nvd.nist.gov/vuln/detail/CVE-2020-15250
Update wiremock from 2.19.0 to 2.32.0.
Update mockito from 3.5.13 to 4.4.0.
Update rest-assured from 4.3.3 to 4.5.1.
Update testcontainers from 1.15.3 to 1.16.3.
=> Update dependencies fixing CVE-2020-36518, CVE-2021-43797

Jenkinsfile, README.md
The doApiLint facility replaces runLintRamlCop
https://dev.folio.org/guides/api-lint/
The doApiDoc facility replaces publishAPI
https://dev.folio.org/guides/api-doc/
The https://dev.folio.org/reference/api/#mod-data-import-converter-storage section of API documentation will be automatically reconfigured:
https://dev.folio.org/reference/api/#explain-gather-config
Please fix the JSON errors, as described in the subsequent comment.
=> MODDICONV-239 FOLIO-3231 Use new api-lint and api-doc CI facilities

mod-data-import-converter-storage-server/pom.xml, mod-data-import-converter-storage-server/src/main/java/org/folio/services/snapshot/ProfileSnapshotServiceImpl.java
Get performance gains by caching job profile snapshots
Once profile snapshots are created, they are never updated. Also, it is retrieved multiple times by actors in the data import system that it makes sense to reduce the response time of this endpoint.
https://issues.folio.org/browse/MODDICONV-254
=> MODDICONV-254 Cache job profile snapshots

mod-data-import-converter-storage-server/pom.xml, pom.xml
Upgrade folio-di-support from 1.4.1 to 1.6.0.
This indirectly upgrades Spring and spring-beans from 5.2.8 to 5.3.20 fixing Remote Code Execution: https://nvd.nist.gov/vuln/detail/CVE-2022-22965
Upgrade Vert.x from 4.3.1 to 4.3.3 fixing SSL in WebClient: https://github.com/vert-x3/wiki/wiki/4.3.2-Release-Notes#vertx-web
=> MODDICONV-260: spring-beans 5.3.20, Vert.x 4.3.3 fixing vulns

mod-data-import-converter-storage-server/src/test/java/org/folio/rest/impl/AbstractRestVerticleTest.java, pom.xml
According to changes in RMB 35.0.0.0 [RMB-937](https://issues.folio.org/browse/RMB-937) add version "1.0.0" when registering the module in AbstractRestVerticleTest
[MODDICONV-269](https://issues.folio.org/browse/MODDICONV-269)
=> MODDICONV-269: Change registration module in tests

mod-data-import-converter-storage-server/src/main/resources/templates/db_scripts/schema.json
downgrade "fromModuleVersion" for `set_deleted_hidden_defaults.sql` script as it's included in MG hotfix
[MODDICONV-270](https://issues.folio.org/browse/MODDICONV-270)
=> MODDICONV-270 Data import job profiles created prior to morning glory are hidden

mod-data-import-converter-storage-server/src/main/resources/log4j2.properties, mod-data-import-converter-storage-server/src/test/resources/log4j2-test.properties
Adjust logging configuration to display datetime in a proper format
Changed logs config file
=> [MODDATAIMP-736] Adjust logging configuration to display datetime in a proper format

mod-data-import-converter-storage-server/src/main/java/org/folio/rest/impl/DataImportProfilesImpl.java, mod-data-import-converter-storage-server/src/test/java/org/folio/rest/impl/JobProfileTest.java
_The "400" error appears when user tries to save edited "Default - Create SRS MARC Authority" job profile with the one of the following updated fields:
a) "Name*" or "Accepted data type*" or "Description";
b) "Name*" and "Accepted data type*" and "Description";_
_ DEFAULT_CREATE_SRS_MARC_AUTHORITY_JOB_PROFILE_ID should be skipped during update request_
https://issues.folio.org/browse/MODDICONV-281 
and more detailed here https://issues.folio.org/browse/UIDATIMP-1318
=> MODDICONV-281 - Enable ability to edit Job profile: Default - Create SRS MARC Authority

mod-data-import-converter-storage-server/src/main/resources/templates/db_scripts/defaultData/default_update_marc_authority_job_profile.sql
_Change: Create SRS MARC Authority Job profile description to "Default job profile for creating MARC authority records. These records are stored in source record storage (SRS). Profile cannot be deleted."_
_update sql script_
https://issues.folio.org/browse/MODDICONV-282 
and https://issues.folio.org/browse/UIDATIMP-1318
=> MODDICONV-282 - Change Job profile: Default - Create SRS MARC Authority description

pom.xml
For 2022 R2 Morning Glory Hot Fix:
Upgrade Spring Framework from 5.2.8.RELEASE to 5.2.22.RELEASE.
The Spring upgrade upgrades spring-beans fixing Spring4Shell Remote Code Execution and Denial of Service (DoS):
https://nvd.nist.gov/vuln/detail/CVE-2022-22965
https://nvd.nist.gov/vuln/detail/CVE-2022-22970
The Spring upgrade upgrades spring-context fixing Improper Handling of Case Sensitivity:
https://nvd.nist.gov/vuln/detail/CVE-2022-22968
The Spring upgrade upgrades spring-expression fixing Denial of Service (DoS):
https://nvd.nist.gov/vuln/detail/CVE-2022-22950
The Spring upgrade upgrades spring-core fixing Improper Input Validation and Improper Output Neutralization for Logs:
https://nvd.nist.gov/vuln/detail/CVE-2021-22060
https://nvd.nist.gov/vuln/detail/CVE-2021-22096
=> MODDICONV-279: Spring 5.2.22 fixing vulnerabilities (Spring4Shell, etc.) MG
