mod-data-import-converter-storage-server/src/main/java/org/folio/dao/AbstractProfileDao.java
mod-data-import-converter-storage-server/src/main/java/org/folio/dao/ProfileDao.java
mod-data-import-converter-storage-server/src/main/java/org/folio/rest/impl/DataImportProfilesImpl.java
mod-data-import-converter-storage-server/src/main/java/org/folio/services/AbstractProfileService.java
mod-data-import-converter-storage-server/src/main/java/org/folio/services/ProfileService.java
mod-data-import-converter-storage-server/src/main/resources/templates/db_scripts/schema.json
mod-data-import-converter-storage-server/src/test/java/org/folio/rest/impl/JobProfileTest.java

If the new job profile name duplicates an existing one
Then the server should not save the record
And should return *jobProfile.duplication.invalid* string as an error message
```
{
"errors": [
{
"message": "jobProfile.duplication.invalid",
"parameters": []
}
],
"total_records": 1
}
```

MODDATAIMP-94 Return error message in case of saving duplicating job profile name

---

pom.xml

Fix tag number from 1.1.1 to v1.1.1

Tag number fix

---

NEWS.md
mod-data-import-converter-storage-server/src/main/java/org/folio/dao/AbstractProfileDao.java
mod-data-import-converter-storage-server/src/main/java/org/folio/dao/ProfileDao.java
mod-data-import-converter-storage-server/src/main/java/org/folio/rest/impl/DataImportProfilesImpl.java
mod-data-import-converter-storage-server/src/main/java/org/folio/services/AbstractProfileService.java
mod-data-import-converter-storage-server/src/main/java/org/folio/services/ActionProfileServiceImpl.java
mod-data-import-converter-storage-server/src/main/java/org/folio/services/JobProfileServiceImpl.java
mod-data-import-converter-storage-server/src/main/java/org/folio/services/MappingProfileServiceImpl.java
mod-data-import-converter-storage-server/src/main/java/org/folio/services/MatchProfileServiceImpl.java
mod-data-import-converter-storage-server/src/main/java/org/folio/services/ProfileService.java
mod-data-import-converter-storage-server/src/main/resources/templates/db_scripts/testData/test_action_profiles.sql
mod-data-import-converter-storage-server/src/main/resources/templates/db_scripts/testData/test_job_profiles.sql
mod-data-import-converter-storage-server/src/main/resources/templates/db_scripts/testData/test_mapping_profiles.sql
mod-data-import-converter-storage-server/src/main/resources/templates/db_scripts/testData/test_matching_profiles.sql
mod-data-import-converter-storage-server/src/test/java/org/folio/rest/impl/ActionProfileTest.java
mod-data-import-converter-storage-server/src/test/java/org/folio/rest/impl/JobProfileTest.java
mod-data-import-converter-storage-server/src/test/java/org/folio/rest/impl/MappingProfileTest.java
mod-data-import-converter-storage-server/src/test/java/org/folio/rest/impl/MatchProfileTest.java
ramls/data-import-converter-storage.raml

- added field 'deleted' to profiles sample data sql scripts;
- changed delete method implementation for action, job, mapping, match profiles;
- changed get method implementation for action, job, mapping, match profiles.

MODDICONV-51 - Change delete implementation for profiles. Mark profiles as deleted

---

NEWS.md
mod-data-import-converter-storage-server/src/main/resources/templates/db_scripts/testData/test_job_profiles.sql
mod-data-import-converter-storage-server/src/main/resources/templates/db_scripts/testData/test_matching_profiles.sql
mod-data-import-converter-storage-server/src/main/resources/templates/db_scripts/testData/test_profile_associations.sql

MODDICONV-56 - Add records in profileAssociations sample data

---

mod-data-import-converter-storage-server/pom.xml
mod-data-import-converter-storage-server/src/main/java/org/folio/dao/association/MasterDetailAssociationDao.java
mod-data-import-converter-storage-server/src/main/java/org/folio/dao/association/MasterDetailAssociationDaoImpl.java
mod-data-import-converter-storage-server/src/main/java/org/folio/services/association/CommonProfileAssociationService.java
ramls/data-import-converter-storage.raml

* Fixed code smells
* Increased jackson-databind version to fix potential security vulnerability

Moddiconv 71

---

NEWS.md
mod-data-import-converter-storage-client/pom.xml
mod-data-import-converter-storage-server/pom.xml
pom.xml

Tmp release 1.4.0

---

NEWS.md
mod-data-import-converter-storage-server/src/main/resources/templates/db_scripts/schema.json
mod-data-import-converter-storage-server/src/main/resources/templates/db_scripts/upgrade_rmb_25.0-29.1.sql

* added script;
* indices definitions have been returned;
* updated "fromModuleVersion" for tables with metadata to replace trigger functions for filling  metadata with  new implementation during the module upgrade;

MODDICONV-112 - Issue with data migration between Edelweiss and Fameflower

---

mod-data-import-converter-storage-server/src/main/java/org/folio/rest/impl/ModTenantAPI.java

JIRA-ticket: https://issues.folio.org/browse/MODDICONV-120

MODDICONV-120: Cannot use the secret button to import MARC bibs and create instances[BUGFIX]

---

NEWS.md

Should be merged along with PRs to all the other modules that have reference to data-import-raml-storage

Updated raml-storage ref - Defined MARC mapping details schema

---

.rancher-pipeline.yml

Rancher config file has to updated to allow deploying the module on Rancher env
Updates include change of project code and docker image name

update rancher config

---

mod-data-import-converter-storage-server/src/main/resources/templates/db_scripts/defaultData/default_edifact_mapping_profiles.sql

[MODDICONV-165](https://issues.folio.org/browse/MODDICONV-165)
Default EDIFACT field mapping profiles for EBSCO, Harrassowitz, and WT Cox EDIFACT.

MODDICONV-165: Create default EDIFACT field mapping profiles, part 2

---

mod-data-import-converter-storage-server/src/main/resources/templates/db_scripts/defaultData/default_edifact_mapping_profiles.sql

- update Amalivre field mapping profile name.
- add missing empty subfields array to vendor reference fields
- refactor poLineNumber to poLineId
- add missing acqUnitIds default subfields
- minor reorder invoiceLineStatus before referenceNumbers

Mapping Profile Updates

---

mod-data-import-converter-storage-server/src/main/java/org/folio/rest/impl/ModTenantAPI.java
mod-data-import-converter-storage-server/src/main/resources/templates/db_scripts/defaultData/default_marc_holdings_job_profile.sql
mod-data-import-converter-storage-server/src/test/java/org/folio/rest/impl/DefaultJobProfileTest.java

Create job profile for marc holdings
- created job profile for marc holdings
- covered data by test case
https://issues.folio.org/browse/MODDICONV-193

MODDICONV-193 Create default profile for importing new MARC Holdings

---

NEWS.md
descriptors/DeploymentDescriptor-template.json
mod-data-import-converter-storage-client/pom.xml
mod-data-import-converter-storage-server/pom.xml
mod-data-import-converter-storage-server/src/main/java/org/folio/rest/impl/DataImportProfilesImpl.java
mod-data-import-converter-storage-server/src/test/java/org/folio/rest/impl/AbstractRestVerticleTest.java
mod-data-import-converter-storage-server/src/test/java/org/folio/unit/AbstractUnitTest.java
pom.xml

Update mod-data-import-converter-storage to new versions of Raml module builder and Vertex.
**Before:**
**After:**
**Before:**
**After:**
**Before:**
**After:**
Raml files have been deleted from client jar, structure and count of generated classes in final client jar remained the same before and after changes.
**Client jar before changes:**
**Client jar after changes:**
New Raml builder generates client classes that not throwing UnsupportedEncodingException in their methods. So in mod-source-record-manager need to delete this catch block when updating to new version of mod-data-import-converter-storage client artifact: https://github.com/folio-org/mod-source-record-manager/blob/master/mod-source-record-manager-server/src/main/java/org/folio/services/JobExecutionServiceImpl.java#L230

MODDICONV-196. Upgrade to RAML Module Builder 33.x

---

NEWS.md
mod-data-import-converter-storage-server/src/main/java/org/folio/dao/AbstractProfileDao.java
mod-data-import-converter-storage-server/src/main/java/org/folio/dao/ProfileDao.java
mod-data-import-converter-storage-server/src/main/java/org/folio/rest/impl/DataImportProfilesImpl.java
mod-data-import-converter-storage-server/src/main/java/org/folio/services/AbstractProfileService.java
mod-data-import-converter-storage-server/src/main/java/org/folio/services/ActionProfileServiceImpl.java
mod-data-import-converter-storage-server/src/main/java/org/folio/services/JobProfileServiceImpl.java
mod-data-import-converter-storage-server/src/main/java/org/folio/services/MappingProfileServiceImpl.java
mod-data-import-converter-storage-server/src/main/java/org/folio/services/MatchProfileServiceImpl.java
mod-data-import-converter-storage-server/src/main/java/org/folio/services/ProfileService.java
mod-data-import-converter-storage-server/src/test/java/org/folio/rest/impl/ActionProfileTest.java
mod-data-import-converter-storage-server/src/test/java/org/folio/rest/impl/JobProfileTest.java
mod-data-import-converter-storage-server/src/test/java/org/folio/rest/impl/MappingProfileTest.java
mod-data-import-converter-storage-server/src/test/java/org/folio/rest/impl/MatchProfileTest.java
ramls/data-import-converter-storage.raml

Provide creation of job profiless using UUID.
- The ability to create a job profile using a UUID
- If the UUID is not used in the request body, the UUID will be generated
- Error output when sending a request with an existing UUID
https://issues.folio.org/browse/MODDICONV-179

MODDICONV-179 Update endpoints for profiles creation to respect UUID

---

NEWS.md
mod-data-import-converter-storage-server/pom.xml
pom.xml

RMB 33.2.2 contains log4j vulnerability fix

Upgrade to RMB 33.2.2

---

mod-data-import-converter-storage-server/src/main/resources/templates/db_scripts/defaultData/default_qm_instance_and_srs_marc_bib_create_job_profile.sql
mod-data-import-converter-storage-server/src/main/resources/templates/db_scripts/defaultData/default_update_qm_holdings_and_srs_marc_holdings_create_job_profile.sql
mod-data-import-converter-storage-server/src/main/resources/templates/db_scripts/defaultData/default_update_qm_instance_and_srs_marc_bib_create_job_profile.sql
mod-data-import-converter-storage-server/src/test/java/org/folio/rest/impl/DefaultJobProfileTest.java

- CHANGE Job profile [quickMARC- Create Holdings and SRS MARC Holdings] TO [quickMARC - Create Holdings and SRS MARC Holdings]
- CHANGE Job profile [quickMARC Derive - Create SRS MARC Bib and Instance] TO [quickMARC - Derive a new SRS MARC Bib and Instance]
[MODDICONV-225](https://issues.folio.org/browse/MODDICONV-225)

MODDICONV-225 Settings : Updates to default quickMARC job profiles

---

mod-data-import-converter-storage-server/src/main/resources/templates/db_scripts/defaultData/default_update_marc_authority_job_profile.sql
mod-data-import-converter-storage-server/src/main/resources/templates/db_scripts/defaultData/default_update_marc_holdings_job_profile.sql

Update action profile names for create authority and holdings
create sql queries for update profile names
[MODDICONV-227](https://issues.folio.org/browse/MODDICONV-227)

MODDICONV-227 Update two action profile names

---

mod-data-import-converter-storage-server/src/main/resources/templates/db_scripts/defaultData/default_update_marc_holdings_job_profile.sql
mod-data-import-converter-storage-server/src/main/resources/templates/db_scripts/defaultData/default_update_qm_holdings_and_srs_marc_holdings_create_job_profile.sql

Change description for holdings field mappings profiles
[MODDICONV-232](https://issues.folio.org/browse/MODDICONV-232)

MODDICONV-232 Change to default - Create MARC holdings field mappings profiles

---

mod-data-import-converter-storage-server/src/main/java/org/folio/dao/AbstractProfileDao.java
pom.xml

Upgrade to RMB v35.0.0
Jira: https://issues.folio.org/browse/MODDICONV-267

[MODDICONV-267] Upgrade to RMB v35.0.0

---

NEWS.md
mod-data-import-converter-storage-client/pom.xml
mod-data-import-converter-storage-server/pom.xml
mod-data-import-converter-storage-server/src/main/resources/templates/db_scripts/data-migration/set_deleted_hidden_defaults.sql
mod-data-import-converter-storage-server/src/main/resources/templates/db_scripts/schema.json
pom.xml

Release v1.14.2
[MODDICONV-273](https://issues.folio.org/browse/MODDICONV-273)

Tmp release v1.14.2

---

mod-data-import-converter-storage-server/src/main/resources/log4j2.properties

Logging should be improved for more productive troubleshooting.
Requirements/Scope:
Check that log4j2.properties doesn't exist or it is aligned with https://wiki.folio.org/display/DD/Folio+logging+solution
Add step "Check logging" to PULL_REQUEST_TEMPLATE.md
AС
The property file and all logging commands are adjusted.

[MODDICONV-271]Logging improvement - Configuration

---

mod-data-import-converter-storage-server/src/main/resources/templates/db_scripts/data-migration/set_administrative_notes.sql
mod-data-import-converter-storage-server/src/main/resources/templates/db_scripts/schema.json

Adding script for migrating admin notes

[MODDICONV-276] Added migration script for administartive notes

---

mod-data-import-converter-storage-server/src/main/resources/templates/db_scripts/data-migration/set_administrative_notes.sql
mod-data-import-converter-storage-server/src/main/resources/templates/db_scripts/schema.json

_Describe the research stage. Add links to blog posts, patterns, libraries or addons used to solve this problem._

MODDICONV-276 Correct script - insert admin notes by index

---

mod-data-import-converter-storage-server/src/main/java/org/folio/dao/AbstractProfileDao.java
mod-data-import-converter-storage-server/src/main/java/org/folio/dao/association/CommonProfileAssociationDao.java
mod-data-import-converter-storage-server/src/main/java/org/folio/dao/association/MasterDetailAssociationDaoImpl.java
mod-data-import-converter-storage-server/src/main/java/org/folio/dao/fieldprotectionsettings/MarcFieldProtectionSettingsDaoImpl.java
mod-data-import-converter-storage-server/src/main/java/org/folio/dao/snapshot/ProfileSnapshotDaoImpl.java
mod-data-import-converter-storage-server/src/main/java/org/folio/rest/impl/ConverterStorageFormsConfigsImpl.java
mod-data-import-converter-storage-server/src/main/java/org/folio/rest/impl/DataImportProfilesImpl.java
mod-data-import-converter-storage-server/src/main/java/org/folio/rest/impl/FieldProtectionSettingsImpl.java
mod-data-import-converter-storage-server/src/main/java/org/folio/rest/impl/ModTenantAPI.java
mod-data-import-converter-storage-server/src/main/java/org/folio/rest/impl/util/ExceptionHelper.java
mod-data-import-converter-storage-server/src/main/java/org/folio/rest/impl/util/RestUtil.java
mod-data-import-converter-storage-server/src/main/java/org/folio/services/AbstractProfileService.java
mod-data-import-converter-storage-server/src/main/java/org/folio/services/MappingProfileServiceImpl.java
mod-data-import-converter-storage-server/src/main/java/org/folio/services/association/CommonProfileAssociationService.java
mod-data-import-converter-storage-server/src/main/java/org/folio/services/snapshot/ProfileSnapshotServiceImpl.java

Improve logs
Changed some  logs level and added some logs changes
Jira: https://issues.folio.org/browse/MODDICONV-233

[MODDICONV-233] Logging improvement

---

README.md

Rename module
Added deprecated section to README

[MODDICONV-259] Add deprecated section to README
